# Generated by Django 5.1.4 on 2024-12-11 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("nominatim_display_name", models.TextField(blank=True, null=True)),
                ("nominatim_coordinates", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="AddressParsed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("house", models.TextField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("near", models.TextField(blank=True, null=True)),
                ("house_number", models.TextField(blank=True, null=True)),
                ("road", models.TextField(blank=True, null=True)),
                ("unit", models.TextField(blank=True, null=True)),
                ("level", models.TextField(blank=True, null=True)),
                ("staircase", models.TextField(blank=True, null=True)),
                ("entrance", models.TextField(blank=True, null=True)),
                ("po_box", models.TextField(blank=True, null=True)),
                ("postcode", models.TextField(blank=True, null=True)),
                ("suburb", models.TextField(blank=True, null=True)),
                ("city_district", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("island", models.TextField(blank=True, null=True)),
                ("state_district", models.TextField(blank=True, null=True)),
                ("state", models.TextField(blank=True, null=True)),
                ("country_region", models.TextField(blank=True, null=True)),
                ("country", models.TextField(blank=True, null=True)),
                ("world_region", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "query",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.query",
                    ),
                ),
            ],
        ),
    ]
